In [2]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC 

trainset = pd.read_csv('SPC-Training.csv', header = None)
testset = pd.read_csv('SPC-Testing.csv', header = None)
trainset['target']= trainset.iloc[:,10:].idxmax(axis=1)
testset['target']= testset.iloc[:,10:].idxmax(axis=1)

clf = SVC(gamma='auto')
clf.fit(trainset.iloc[:,:10], trainset.target)
clf.score(trainset.iloc[:,:10], trainset.target)
report = pd.DataFrame(np.zeros((90,6)), columns=['kernel','degree','c_searchline', 'num_of_vectors','score_train', 'score_test'])
Kernels =['poly','linear', 'rbf', 'sigmoid']
c_searchline = [.015, .01 , 0.25, 0.3, 0.4]
degrees =[2,3,4,5]
index = 0 

for c in c_searchline : 
    for k in Kernels :         
        for deg in degrees:
            
            model = SVC(gamma='auto', C = c, kernel = k , degree = deg , verbose = True , decision_function_shape = 'ovr')
            index+=1
    
            model.fit(trainset.iloc[:,:10] ,trainset.target)
            nSV= len(model.support_)
            score_train =  model.score(trainset.iloc[:,:10], trainset.target)
            score_test =  model.score(testset.iloc[:,:10] ,testset.target)
            report.iloc[index]= [k,deg,c,nSV, score_train , score_test]
            
final_model = SVC(C=0.2 , kernel ='poly', degree= 2, decision_function_shape='ovr')
final_model.fit(trainset.iloc[:,:10], trainset.target)
testset['predict']= final_model.predict(testset.iloc[:,:10])
from sklearn.metrics import confusion_matrix        
print (confusion_matrix(testset.target,testset.predict))
        

[LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][[92  0  1  1  1  4  1]
 [ 2 22  1  0  0  0  0]
 [ 2  0 22  1  0  0  0]
 [ 1  0  3 18  3  0  0]
 [ 2  0  0  1 22  0  0]
 [ 0  0  0  0  0 25  0]
 [ 3  0  0  0  0  0 22]]


In [3]:
final_model = SVC(C=0.2 , kernel ='rbf', degree= 2, decision_function_shape='ovr')
final_model.fit(trainset.iloc[:,:10], trainset.target)
testset['predict']= final_model.predict(testset.iloc[:,:10])
from sklearn.metrics import confusion_matrix        
print (confusion_matrix(testset.target,testset.predict))

[[94  0  1  2  1  0  2]
 [17  7  1  0  0  0  0]
 [16  0  8  1  0  0  0]
 [ 6  0  0 17  2  0  0]
 [ 3  0  0  1 21  0  0]
 [ 0  0  0  0  0 25  0]
 [ 0  0  0  0  0  0 25]]


In [4]:
final_model = SVC(C=0.2 , kernel ='sigmoid', degree= 2, decision_function_shape='ovr')
final_model.fit(trainset.iloc[:,:10], trainset.target)
testset['predict']= final_model.predict(testset.iloc[:,:10])
from sklearn.metrics import confusion_matrix        
print (confusion_matrix(testset.target,testset.predict))

[[100   0   0   0   0   0   0]
 [ 25   0   0   0   0   0   0]
 [ 25   0   0   0   0   0   0]
 [ 25   0   0   0   0   0   0]
 [ 25   0   0   0   0   0   0]
 [ 25   0   0   0   0   0   0]
 [ 25   0   0   0   0   0   0]]


In [5]:
final_model = SVC(C=0.2 , kernel ='linear', degree= 2, decision_function_shape='ovr')
final_model.fit(trainset.iloc[:,:10], trainset.target)
testset['predict']= final_model.predict(testset.iloc[:,:10])
from sklearn.metrics import confusion_matrix        
print (confusion_matrix(testset.target,testset.predict))

[[100   0   0   0   0   0   0]
 [ 25   0   0   0   0   0   0]
 [ 25   0   0   0   0   0   0]
 [ 25   0   0   0   0   0   0]
 [ 25   0   0   0   0   0   0]
 [ 25   0   0   0   0   0   0]
 [ 25   0   0   0   0   0   0]]
